name: Test 1
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Train Model
        run: |
          pip install -r requirements.txt
          python testscript.py
      - name: CML Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        run: |
          echo "## Model Performance" > report.md
          cat results.txt >> report.md
          cml comment create report.md